  0%|                              | 0/8812 [01:46<?, ?it/s]
Traceback (most recent call last):
  File "/home/wg25r/remeow/DinoMeow/main.py", line 91, in <module>
    trainer.train()
  File "/home/wg25r/remeow/DinoMeow/trainer.py", line 157, in train
    self.train_epoch()
  File "/home/wg25r/remeow/DinoMeow/trainer.py", line 102, in train_epoch
    train_pred = self.train_step(X_student, X_teacher, Y, ROI)
  File "/home/wg25r/remeow/DinoMeow/trainer.py", line 52, in train_step
    teacher_pred = torch.sigmoid(self.teacher(X_teacher) / self.args.temp)
  File "/home/wg25r/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wg25r/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wg25r/.local/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 172, in forward
    raise RuntimeError("module must have its parameters and buffers "
RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cuda:1
Traceback (most recent call last):
  File "/home/wg25r/remeow/DinoMeow/main.py", line 91, in <module>
    trainer.train()
  File "/home/wg25r/remeow/DinoMeow/trainer.py", line 157, in train
    self.train_epoch()
  File "/home/wg25r/remeow/DinoMeow/trainer.py", line 102, in train_epoch
    train_pred = self.train_step(X_student, X_teacher, Y, ROI)
  File "/home/wg25r/remeow/DinoMeow/trainer.py", line 52, in train_step
    teacher_pred = torch.sigmoid(self.teacher(X_teacher) / self.args.temp)
  File "/home/wg25r/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wg25r/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wg25r/.local/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 172, in forward
    raise RuntimeError("module must have its parameters and buffers "
RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cuda:1
Exception in thread Thread-4 (_pin_memory_loop):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wg25r/.local/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 55, in _pin_memory_loop
    do_one_step()
  File "/home/wg25r/.local/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 32, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/home/wg25r/.local/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 496, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.10/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/usr/lib/python3.10/multiprocessing/resource_sharer.py", line 86, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
Exception ignored in atexit callback: <function _MultiProcessingDataLoaderIter._clean_up_worker at 0x714f861805e0>
Traceback (most recent call last):
  File "/home/wg25r/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1471, in _clean_up_worker
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/usr/lib/python3.10/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python3.10/multiprocessing/popen_fork.py", line 40, in wait
    if not wait([self.sentinel], timeout):
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt:
Exception ignored in atexit callback: <function _MultiProcessingDataLoaderIter._clean_up_worker at 0x714f861805e0>
Traceback (most recent call last):
  File "/home/wg25r/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1471, in _clean_up_worker
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/usr/lib/python3.10/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python3.10/multiprocessing/popen_fork.py", line 40, in wait
    if not wait([self.sentinel], timeout):
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt:
Exception ignored in atexit callback: <function _MultiProcessingDataLoaderIter._clean_up_worker at 0x714f861805e0>
Traceback (most recent call last):
  File "/home/wg25r/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1471, in _clean_up_worker
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/usr/lib/python3.10/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python3.10/multiprocessing/popen_fork.py", line 40, in wait
    if not wait([self.sentinel], timeout):
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt:
